<a href="https://colab.research.google.com/github/AnanyaGodse/DJS-Compute-Tasks/blob/main/Task%206/Task%203%20-%20Bagging.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing Libraries

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, BaggingClassifier
from sklearn.metrics import accuracy_score, multilabel_confusion_matrix, classification_report

# Loading and Processing the Dataset

In [ ]:
df = pd.read_csv("churndata_processed.csv")
df

months  multiple    gb_mon  security  backup  protection  support  \
0       0.00         0  0.094118         0       0           1        0   
1       0.00         1  0.200000         0       1           0        0   
2       0.25         1  0.611765         0       0           0        0   
3       0.25         0  0.141176         0       1           1        0   
4       0.50         1  0.164706         0       0           0        0   
...      ...       ...       ...       ...     ...         ...      ...   
7038    1.00         0  0.000000         0       0           0        0   
7039    0.25         1  0.282353         1       0           1        1   
7040    1.00         1  0.694118         0       1           1        0   
7041    0.00         0  0.200000         1       0           0        0   
7042    1.00         0  0.129412         1       0           1        1   

      unlimited  contract  paperless  ...  payment_Credit Card  \
0             0       0.0          1  ...                    0   
1             1       0.0          1  ...                    1   
2             1       0.0          1  ...                    0   
3             1       0.0          1  ...                    0   
4             1       0.0          1  ...                    0   
...         ...       ...        ...  ...                  ...   
7038          0       1.0          1  ...                    0   
7039          1       0.5          1  ...                    0   
7040          1       0.5          1  ...                    1   
7041          1       0.0          1  ...                    0   
7042          1       1.0          1  ...                    0   

      payment_Mailed Check  internet_type_DSL  internet_type_Fiber Optic  \
0                        0                  1                          0   
1                        0                  0                          1   
2                        0                  0                          1   
3                        0                  0                          1   
4                        0                  0                          1   
...                    ...                ...                        ...   
7038                     0                  0                          0   
7039                     1                  0                          0   
7040                     0                  0                          1   
7041                     0                  1                          0   
7042                     0                  0                          1   

      internet_type_None  offer_Offer A  offer_Offer B  offer_Offer C  \
0                      0              0              0              0   
1                      0              0              0              0   
2                      0              0              0              0   
3                      0              0              0              1   
4                      0              0              0              1   
...                  ...            ...            ...            ...   
7038                   1              0              0              0   
7039                   0              0              0              1   
7040                   0              0              0              0   
7041                   0              0              0              0   
7042                   0              0              0              0   

      offer_Offer D  offer_Offer E  
0                 0              0  
1                 0              1  
2                 1              0  
3                 0              0  
4                 0              0  
...             ...            ...  
7038              0              0  
7039              0              0  
7040              0              0  
7041              0              0  
7042              0              0  

[7043 rows x 23 columns]

In [ ]:
df.head()

months  multiple    gb_mon  security  backup  protection  support  \
0    0.00         0  0.094118         0       0           1        0   
1    0.00         1  0.200000         0       1           0        0   
2    0.25         1  0.611765         0       0           0        0   
3    0.25         0  0.141176         0       1           1        0   
4    0.50         1  0.164706         0       0           0        0   

   unlimited  contract  paperless  ...  payment_Credit Card  \
0          0       0.0          1  ...                    0   
1          1       0.0          1  ...                    1   
2          1       0.0          1  ...                    0   
3          1       0.0          1  ...                    0   
4          1       0.0          1  ...                    0   

   payment_Mailed Check  internet_type_DSL  internet_type_Fiber Optic  \
0                     0                  1                          0   
1                     0                  0                          1   
2                     0                  0                          1   
3                     0                  0                          1   
4                     0                  0                          1   

   internet_type_None  offer_Offer A  offer_Offer B  offer_Offer C  \
0                   0              0              0              0   
1                   0              0              0              0   
2                   0              0              0              0   
3                   0              0              0              1   
4                   0              0              0              1   

   offer_Offer D  offer_Offer E  
0              0              0  
1              0              1  
2              1              0  
3              0              0  
4              0              0  

[5 rows x 23 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 23 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   months                     7043 non-null   float64
 1   multiple                   7043 non-null   int64  
 2   gb_mon                     7043 non-null   float64
 3   security                   7043 non-null   int64  
 4   backup                     7043 non-null   int64  
 5   protection                 7043 non-null   int64  
 6   support                    7043 non-null   int64  
 7   unlimited                  7043 non-null   int64  
 8   contract                   7043 non-null   float64
 9   paperless                  7043 non-null   int64  
 10  monthly                    7043 non-null   float64
 11  satisfaction               7043 non-null   float64
 12  churn_value                7043 non-null   int64  
 13  payment_Credit Card        7043 non-null   int64

In [ ]:
df.isnull().sum()

months                       0
multiple                     0
gb_mon                       0
security                     0
backup                       0
protection                   0
support                      0
unlimited                    0
contract                     0
paperless                    0
monthly                      0
satisfaction                 0
churn_value                  0
payment_Credit Card          0
payment_Mailed Check         0
internet_type_DSL            0
internet_type_Fiber Optic    0
internet_type_None           0
offer_Offer A                0
offer_Offer B                0
offer_Offer C                0
offer_Offer D                0
offer_Offer E                0
dtype: int64

In [ ]:
# Accepted Offer A = 1, B = 2, C = 3, D = 4, E = 5; All Offers Rejected = 0
df["offer_Offer B"] = df["offer_Offer B"].replace({1:2})
df["offer_Offer C"] = df["offer_Offer C"].replace({1:3})
df["offer_Offer D"] = df["offer_Offer D"].replace({1:4})
df["offer_Offer E"] = df["offer_Offer E"].replace({1:5})

In [ ]:
df["Accepted Offer"] = df.iloc[:, -5:].max(axis=1)
df

months  multiple    gb_mon  security  backup  protection  support  \
0       0.00         0  0.094118         0       0           1        0   
1       0.00         1  0.200000         0       1           0        0   
2       0.25         1  0.611765         0       0           0        0   
3       0.25         0  0.141176         0       1           1        0   
4       0.50         1  0.164706         0       0           0        0   
...      ...       ...       ...       ...     ...         ...      ...   
7038    1.00         0  0.000000         0       0           0        0   
7039    0.25         1  0.282353         1       0           1        1   
7040    1.00         1  0.694118         0       1           1        0   
7041    0.00         0  0.200000         1       0           0        0   
7042    1.00         0  0.129412         1       0           1        1   

      unlimited  contract  paperless  ...  payment_Mailed Check  \
0             0       0.0          1  ...                     0   
1             1       0.0          1  ...                     0   
2             1       0.0          1  ...                     0   
3             1       0.0          1  ...                     0   
4             1       0.0          1  ...                     0   
...         ...       ...        ...  ...                   ...   
7038          0       1.0          1  ...                     0   
7039          1       0.5          1  ...                     1   
7040          1       0.5          1  ...                     0   
7041          1       0.0          1  ...                     0   
7042          1       1.0          1  ...                     0   

      internet_type_DSL  internet_type_Fiber Optic  internet_type_None  \
0                     1                          0                   0   
1                     0                          1                   0   
2                     0                          1                   0   
3                     0                          1                   0   
4                     0                          1                   0   
...                 ...                        ...                 ...   
7038                  0                          0                   1   
7039                  0                          0                   0   
7040                  0                          1                   0   
7041                  1                          0                   0   
7042                  0                          1                   0   

      offer_Offer A  offer_Offer B  offer_Offer C  offer_Offer D  \
0                 0              0              0              0   
1                 0              0              0              0   
2                 0              0              0              4   
3                 0              0              3              0   
4                 0              0              3              0   
...             ...            ...            ...            ...   
7038              0              0              0              0   
7039              0              0              3              0   
7040              0              0              0              0   
7041              0              0              0              0   
7042              0              0              0              0   

      offer_Offer E  Accepted Offer  
0                 0               0  
1                 5               5  
2                 0               4  
3                 0               3  
4                 0               3  
...             ...             ...  
7038              0               0  
7039              0               3  
7040              0               0  
7041              0               0  
7042              0               0  

[7043 rows x 24 columns]

In [ ]:
df.drop(columns=["offer_Offer A","offer_Offer B", "offer_Offer C", "offer_Offer D", "offer_Offer E"], inplace=True)
df

months  multiple    gb_mon  security  backup  protection  support  \
0       0.00         0  0.094118         0       0           1        0   
1       0.00         1  0.200000         0       1           0        0   
2       0.25         1  0.611765         0       0           0        0   
3       0.25         0  0.141176         0       1           1        0   
4       0.50         1  0.164706         0       0           0        0   
...      ...       ...       ...       ...     ...         ...      ...   
7038    1.00         0  0.000000         0       0           0        0   
7039    0.25         1  0.282353         1       0           1        1   
7040    1.00         1  0.694118         0       1           1        0   
7041    0.00         0  0.200000         1       0           0        0   
7042    1.00         0  0.129412         1       0           1        1   

      unlimited  contract  paperless   monthly  satisfaction  churn_value  \
0             0       0.0          1  0.212935          0.50            1   
1             1       0.0          1  0.620896          0.50            1   
2             1       0.0          1  0.768159          0.25            1   
3             1       0.0          1  0.798507          0.25            1   
4             1       0.0          1  0.579602          0.25            1   
...         ...       ...        ...       ...           ...          ...   
7038          0       1.0          1  0.028856          1.00            0   
7039          1       0.5          1  0.662189          0.50            0   
7040          1       0.5          1  0.845274          0.75            0   
7041          1       0.0          1  0.112935          0.75            0   
7042          1       1.0          1  0.869652          0.75            0   

      payment_Credit Card  payment_Mailed Check  internet_type_DSL  \
0                       0                     0                  1   
1                       1                     0                  0   
2                       0                     0                  0   
3                       0                     0                  0   
4                       0                     0                  0   
...                   ...                   ...                ...   
7038                    0                     0                  0   
7039                    0                     1                  0   
7040                    1                     0                  0   
7041                    0                     0                  1   
7042                    0                     0                  0   

      internet_type_Fiber Optic  internet_type_None  Accepted Offer  
0                             0                   0               0  
1                             1                   0               5  
2                             1                   0               4  
3                             1                   0               3  
4                             1                   0               3  
...                         ...                 ...             ...  
7038                          0                   1               0  
7039                          0                   0               3  
7040                          1                   0               0  
7041                          0                   0               0  
7042                          1                   0               0  

[7043 rows x 19 columns]

In [ ]:
df["Accepted Offer"].value_counts()

0    3877
2     824
5     805
4     602
1     520
3     415
Name: Accepted Offer, dtype: int64

The data is imbalanced in the sense that the number of offer rejections is way higher than offer acceptance for any of the 5 kinds of offers. This is a class-imbalance problem.

One way to solve this kind of problem is to use ensemble learning methods. Ensemble methods combine the insights obtained from multiple learning models to facilitate accurate and improved decisions.

# Train Test Split

In [ ]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Fitting the Model

In [ ]:
clf = BaggingClassifier(estimator=RandomForestClassifier())
clf.fit(X_train, y_train)

BaggingClassifier(estimator=RandomForestClassifier())

# Predicting Results for Testing Data

In [ ]:
predictions = clf.predict(X_test)
predictions

array([0, 0, 0, ..., 0, 3, 5])

# Performance Evaluation

In [ ]:
acc_score = accuracy_score(y_test, predictions)
print("Accuracy Score: ", acc_score)

Accuracy Score:  0.525195173882186


In [ ]:
cm = multilabel_confusion_matrix(y_test, predictions, labels=["0", "1", "2", "3", "4", "5"])
print(cm)

[[[ 145  476]
  [ 159  629]]

 [[1260   50]
  [  71   28]]

 [[1209   39]
  [ 131   30]]

 [[1303   15]
  [  88    3]]

 [[1269   33]
  [  98    9]]

 [[1190   56]
  [ 122   41]]]


In [ ]:
cr = classification_report(y_test, predictions)
print(cr)

              precision    recall  f1-score   support

           0       0.57      0.80      0.66       788
           1       0.36      0.28      0.32        99
           2       0.43      0.19      0.26       161
           3       0.17      0.03      0.06        91
           4       0.21      0.08      0.12       107
           5       0.42      0.25      0.32       163

    accuracy                           0.53      1409
   macro avg       0.36      0.27      0.29      1409
weighted avg       0.47      0.53      0.47      1409



We should use precision, recall and f1 score to evaluate the performance of an imbalanced dataset as precision measures the proportion of correctly predicted positive instances among all predicted positives, while recall measures the proportion of correctly predicted positive instances among all actual positives.
F1 score is the harmonic mean of precision and recall and thus useful.